### PR TITLE
"A tiny Discord bot."

### PR DESCRIPTION
**Pull request by shikhir-arora**
And so it begins... 📜

### CODE REVIEW

**Comment by siku2** [comment]
What the duck

**Comment by shikhir-arora** [comment]
@siku2 No words..but you can have the honor of merging this beautiful PR. 😂

**Comment by siku2** [comment]
I'm grateful

**Comment by shikhir-arora** [comment]
Just as I do the idiotic thing of deleting my master branch. 🤦‍♂️ 

10/10.

Best PR ever. 👌 
screen shot 2017-11-17 at 9 29 39 am

**Pull request merged**
