### PR TITLE
Moving up the recursion level

### PR DESCRIPTION
**Pull request by siku2**
Though the permission system is **anything but tested** and probably still has a lot of bugs I think the basics are there. Enough so to justify this pull request.

Since this branch has become a free-for-all anyway containing lots of commits that are completely unrelated it might as well be merged so that development can continue there.

---
This change is not (muhaha) [Reviewable](https://reviewable.io/reviews/gieseladev/giesela/61)

### CODE REVIEW

**Comment by siku2** [comment]
@shikhir-arora Do we really need "Reviewable"? When I used it I didn't notice any real benefits.
As far as I'm concerned all it has is a different, more convoluted design...

**Comment by siku2** [comment]
Gotta love how Travis hates me now 🤷‍♂️

**Comment by shikhir-arora** [comment]
> @shikhir-arora Do we really need "Reviewable"? When I used it I didn't notice any real benefits.
> As far as I'm concerned all it has is a different, more convoluted design...

@siku2 Nah, feel free to remove (or just ignore it).

**Comment by siku2** [comment]
@shikhir-arora it's not like I mind it being there, it's just weird that it uses your account to edit my messages xD. 
If you actually use it that's fine though.

**Comment by shikhir-arora** [comment]
> @shikhir-arora it's not like I mind it being there, it's just weird that it uses your account to edit my messages xD.
> If you actually use it that's fine though.

I don't mind it, but the mobile interface (unless it improved recently) makes it a pain to use. It shouldn't affect the PR in any way (for checks) and using the built-in review system works just fine. So safe to ignore for now. Sometimes it comes in handy for "complex" code reviews IMO.

**Review by shikhir-arora — APPROVED** [review]
@siku2 I read through everything again, now that the CI is good this certainly looks good to merge up the recursion level since that's the next logical "step." 👍

**Comment by siku2** [comment]
Yeah I'm certain there still are a few bugs in there and it's definitely going to need some polish in the future, but because this branch contains so many other features I'm going to merge it so I can continue development.

**Pull request merged**
