### PR TITLE
Refresh lavalink config

### PR DESCRIPTION
**Pull request by siku2**
What can I say, I like "real" PRs

---
This change is [Reviewable](https://reviewable.io/reviews/gieseladev/giesela/54)

### CODE REVIEW

**Review by shikhir-arora — COMMENTED** [review]
> Reviewed 35 of 35 files at r4.
> *[Reviewable](https://reviewable.io/reviews/gieseladev/giesela/54)* status: all files reviewed, 1 unresolved discussion (waiting on @siku2)

___
*[giesela/cogs/player.py, line 405 at r4](https://reviewable.io/reviews/gieseladev/giesela/54#-LM-7NcG4pqO9TmydHjB:-LM-7NcG4pqO9TmydHjC:b-mvsjap) ([raw file](https://github.com/gieseladev/giesela/blob/ccdde7e875f184962ad51f2f53e183443dfd200d/giesela/cogs/player.py#L405)):*
> ```Python
>                 _progress_guess = player.progress / player.current_entry.entry.duration
> 
>             raise commands.CommandError("Down for maintenance?")
> ```

I may be overlooking something, but is there a reason for this? This seems to disable lyrics. 

Edit: I assume it's because the player duration can't be fully detected yet?

**Review by shikhir-arora — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gieseladev/giesela/54)* status: all files reviewed, 2 unresolved discussions (waiting on @siku2)

___
*[data/config.yml, line 66 at r4](https://reviewable.io/reviews/gieseladev/giesela/54#-LM-ANeLCYdk2iwoFQXM:-LM-ANeLCYdk2iwoFQXN:b-wdpjf0) ([raw file](https://github.com/gieseladev/giesela/blob/ccdde7e875f184962ad51f2f53e183443dfd200d/data/config.yml#L66)):*
> ```YAML
>       # limits for queue and history (0 for infinite)
>       queue_limit: ~
>       history_limit: 200
> ```

Nit: Just to remember, Lavalink has a max YouTube playlist load amount that we should consider when factoring this decision, moreso for selfhosters.

**Review by siku2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/gieseladev/giesela/54)* status: all files reviewed, 2 unresolved discussions (waiting on @siku2)

___
*[data/config.yml, line 66 at r4](https://reviewable.io/reviews/gieseladev/giesela/54#-LM-ANeLCYdk2iwoFQXM:-LM2Au6VEcgyPMrQtqZj:b-mk641p) ([raw file](https://github.com/gieseladev/giesela/blob/ccdde7e875f184962ad51f2f53e183443dfd200d/data/config.yml#L66)):*
<details><summary><i>Previously, shikhir-arora (Shikhir Arora) wrote…</i></summary><blockquote>

Nit: Just to remember, Lavalink has a max YouTube playlist load amount that we should consider when factoring this decision, moreso for selfhosters. 
</blockquote></details>

Yeah but those limits represent hard limits for the queue/history deques. Sure, Lavalink might not return all entries in a playlist, but this isn't the place to pay attention to that. I'm not even sure whether we want to pay any attention to that anyway...
___
*[giesela/cogs/player.py, line 405 at r4](https://reviewable.io/reviews/gieseladev/giesela/54#-LM-7NcG4pqO9TmydHjB:-LM2BS3v-xxMkZkyxuiD:bd2t2a2) ([raw file](https://github.com/gieseladev/giesela/blob/ccdde7e875f184962ad51f2f53e183443dfd200d/giesela/cogs/player.py#L405)):*
<details><summary><i>Previously, shikhir-arora (Shikhir Arora) wrote…</i></summary><blockquote>

I may be overlooking something, but is there a reason for this? This seems to disable lyrics.
</blockquote></details>

Yes, it does disable lyrics for now. The problem is that the lyrics file was depending too much on the "static_config", a terrible system from the ancient times which would consist of only the default values. In order to make it work with the new system I would've had to rewrite the entire thing, but instead I think it's better to wait for GiTils.

**Review by shikhir-arora — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/gieseladev/giesela/54)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
