### PR TITLE
Add default voice channel 

### PR DESCRIPTION
**Pull request by shikhir-arora**
Work in progress

### CODE REVIEW

**Comment by shikhir-arora** [comment]
[auto-summon not working as expected](https://trello.com/c/e1n1MDEP/40-auto-summon-not-working-as-expected)

thoughts?

**Comment by shikhir-arora** [comment]
Might be better to use the `\json` config and specify multiple default voice channels and then have Giesela try to join them all, so it’s not just one server. (I see why you did the `find_home_channel` the way you did)

**Comment by shikhir-arora** [comment]
@siku2 You like that idea (the one above)?

If so I will implement it. Just like `bound channels` with with multiple JSON-valued channels. 

Basically let Giesela try to connect to the channels in `default_voice = ["", ""]\json` (if not `None`), and if that fails use `find_home_channel` as it does currently.

**Comment by siku2** [comment]
I support the idea but it should probably be a dictionary whose keys are the server ids and the value is the corresponding voice_channel id.

```python
{
  "<server_id>": "<voice_channel_id>"
}
```

Inside the `find_home_channel` one could then check `if server.id in self.config.default_voice`. If that's the case, just `return server.get_channel(id)` (id stands for the voice channel id, so `id = self.config.default_voice[server.id]`).

If the server doesn't have a default_voice channel assigned to it, continue with the old code.

**Review by siku2 — CHANGES_REQUESTED** [review]
Refer to my comment... Totally forgot to actually write it as a review

**Comment by shikhir-arora** [comment]
@siku2 Sounds good, yeah. Will get that squared away.

**Comment by shikhir-arora** [comment]
Will close this for now.

**Pull request closed without merging**
